// src/app/shared/status-toggle.component.ts
import { Component, Input, signal } from '@angular/core';
import { NgClass } from '@angular/common';

@Component({
  selector: 'app-status-toggle',
  standalone: true,
  imports: [NgClass],
  template: `
    <label class="flex items-center gap-2">
      <input
        type="checkbox"
        [checked]="checked"
        (change)="toggle($event)"
        class="toggle-input"
      />
      <span class="text-sm text-muted-foreground">{{ label }}</span>
    </label>
  `,
})
export class StatusToggleComponent {
  @Input() checked = false;
  @Input() label = 'Activar o desactivar';

  readonly checkedSignal = signal(this.checked);

  toggle(event: Event) {
    const target = event.target as HTMLInputElement;
    this.checkedSignal.set(target.checked);
  }
}

// src/components/shared/StatusToggle.tsx
import { Switch } from "@/components/ui/switch";
import { cn } from "@/lib/utils";

interface StatusToggleProps {
  checked: boolean;
  onCheckedChange?: (checked: boolean) => void;
  label?: string;
}

export function StatusToggle({ checked, onCheckedChange, label = "Activar o desactivar" }: StatusToggleProps) {
  return (
    <div className="flex items-center gap-2">
      <Switch
        checked={checked}
        onCheckedChange={onCheckedChange}
        className={cn(
          "data-[state=checked]:bg-success",
          "data-[state=unchecked]:bg-muted"
        )}
      />
      <span className="text-sm text-muted-foreground">{label}</span>
    </div>
  );
}
