// src/app/shared/status-badge.component.ts
import { Component, Input } from '@angular/core';
import { NgClass } from '@angular/common';

type StatusType = 'active' | 'inactive' | 'pending' | 'open';

const statusConfig: Record<StatusType, { className: string; defaultLabel: string }> = {
  active: { className: 'badge-active', defaultLabel: 'Activo' },
  inactive: { className: 'badge-inactive', defaultLabel: 'Inactivo' },
  pending: { className: 'badge-pending', defaultLabel: 'Pendiente' },
  open: { className: 'badge-info', defaultLabel: 'Abierto' },
};

@Component({
  selector: 'app-status-badge',
  standalone: true,
  imports: [NgClass],
  template: `
    <span [ngClass]="className">{{ label || defaultLabel }}</span>
  `,
})
export class StatusBadgeComponent {
  @Input({ required: true }) status: StatusType = 'active';
  @Input() label?: string;

  get className() {
    return statusConfig[this.status].className;
  }

  get defaultLabel() {
    return statusConfig[this.status].defaultLabel;
  }
}

// src/components/shared/StatusBadge.tsx
import { cn } from "@/lib/utils";

type StatusType = "active" | "inactive" | "pending" | "open";

interface StatusBadgeProps {
  status: StatusType;
  label?: string;
}

const statusConfig: Record<StatusType, { class: string; defaultLabel: string }> = {
  active: { class: "badge-active", defaultLabel: "Activo" },
  inactive: { class: "badge-inactive", defaultLabel: "Inactivo" },
  pending: { class: "badge-pending", defaultLabel: "Pendiente" },
  open: { class: "badge-info", defaultLabel: "Abierto" },
};

export function StatusBadge({ status, label }: StatusBadgeProps) {
  const config = statusConfig[status];
  
  return (
    <span className={cn(config.class)}>
      {label || config.defaultLabel}
    </span>
  );
}
