// src/components/layout/AppSidebar.tsx
import { useState } from "react";
import { NavLink, useLocation } from "react-router-dom";
import {
  Users,
  FolderKanban,
  Tags,
  FileText,
  Settings2,
  BarChart3,
  ChevronLeft,
  ChevronRight,
} from "lucide-react";
import { cn } from "@/lib/utils";

const menuItems = [
  { title: "Usuarios", url: "/usuarios", icon: Users },
  { title: "Proyectos", url: "/proyectos", icon: FolderKanban },
  { title: "Categorías", url: "/categorias", icon: Tags },
  { title: "Plantillas", url: "/plantillas", icon: FileText },
  { title: "Gestión", url: "/gestion", icon: Settings2 },
  { title: "Reportes", url: "/reportes", icon: BarChart3 },
];

export function AppSidebar() {
  const [collapsed, setCollapsed] = useState(false);
  const location = useLocation();

  return (
    <aside
      className={cn(
        "h-screen bg-sidebar flex flex-col transition-all duration-300 ease-in-out sticky top-0",
        collapsed ? "w-16" : "w-64"
      )}
    >
      {/* Logo */}
      <div className="flex items-center h-16 px-4 border-b border-sidebar-border">
        <div className="flex items-center gap-3 overflow-hidden">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-primary to-blue-400 flex items-center justify-center flex-shrink-0">
            <span className="text-white font-bold text-sm">A</span>
          </div>
          {!collapsed && (
            <div className="animate-fade-in">
              <h1 className="font-bold text-sidebar-foreground text-lg leading-tight">atlantic</h1>
              <p className="text-[10px] text-sidebar-muted leading-none">Quantum Innovations</p>
            </div>
          )}
        </div>
      </div>

      {/* Navigation */}
      <nav className="flex-1 py-4 px-2 overflow-y-auto">
        <ul className="space-y-1">
          {menuItems.map((item) => {
            const isActive = location.pathname === item.url || 
              (item.url === "/proyectos" && location.pathname === "/");
            
            return (
              <li key={item.title}>
                <NavLink
                  to={item.url}
                  className={cn(
                    "flex items-center gap-3 px-3 py-2.5 rounded-lg transition-all duration-150",
                    "hover:bg-sidebar-accent",
                    isActive
                      ? "bg-primary text-primary-foreground shadow-md"
                      : "text-sidebar-foreground/80 hover:text-sidebar-foreground"
                  )}
                >
                  <item.icon className={cn("w-5 h-5 flex-shrink-0", isActive && "text-primary-foreground")} />
                  {!collapsed && (
                    <span className="font-medium text-sm animate-fade-in">{item.title}</span>
                  )}
                </NavLink>
              </li>
            );
          })}
        </ul>
      </nav>

      {/* Collapse button */}
      <div className="p-2 border-t border-sidebar-border">
        <button
          onClick={() => setCollapsed(!collapsed)}
          className="w-full flex items-center justify-center gap-2 px-3 py-2 rounded-lg text-sidebar-foreground/60 hover:text-sidebar-foreground hover:bg-sidebar-accent transition-colors"
        >
          {collapsed ? (
            <ChevronRight className="w-5 h-5" />
          ) : (
            <>
              <ChevronLeft className="w-5 h-5" />
              <span className="text-sm">Colapsar</span>
            </>
          )}
        </button>
      </div>
    </aside>
  );
}

// src/app/layout/app-sidebar.component.ts
import { Component, signal, computed, inject } from '@angular/core';
import { RouterLink, RouterLinkActive, Router } from '@angular/router';
import { NgClass, NgFor, NgIf } from '@angular/common';
import { IconComponent } from '../ui/icon.component';

const menuItems = [
  { title: 'Usuarios', url: '/usuarios', icon: 'users' },
  { title: 'Proyectos', url: '/proyectos', icon: 'folder' },
  { title: 'Categorías', url: '/categorias', icon: 'tags' },
  { title: 'Plantillas', url: '/plantillas', icon: 'file-text' },
  { title: 'Gestión', url: '/gestion', icon: 'settings' },
  { title: 'Reportes', url: '/reportes', icon: 'bar-chart' },
];

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, NgClass, NgFor, NgIf, IconComponent],
  template: `
    <aside
      class="h-screen bg-sidebar flex flex-col transition-all duration-300 ease-in-out sticky top-0"
      [ngClass]="{ 'w-16': collapsed(), 'w-64': !collapsed() }"
    >
      <div class="flex items-center h-16 px-4 border-b border-sidebar-border">
        <div class="flex items-center gap-3 overflow-hidden">
          <div
            class="w-8 h-8 rounded-lg bg-gradient-to-br from-primary to-blue-400 flex items-center justify-center flex-shrink-0"
          >
            <span class="text-white font-bold text-sm">A</span>
          </div>
          <div *ngIf="!collapsed()" class="animate-fade-in">
            <h1 class="font-bold text-sidebar-foreground text-lg leading-tight">atlantic</h1>
            <p class="text-[10px] text-sidebar-muted leading-none">Quantum Innovations</p>
          </div>
        </div>
      </div>

      <nav class="flex-1 py-4 px-2 overflow-y-auto">
        <ul class="space-y-1">
          <li *ngFor="let item of menuItems">
            <a
              [routerLink]="item.url"
              routerLinkActive="bg-primary text-primary-foreground shadow-md"
              [routerLinkActiveOptions]="{ exact: true }"
              class="flex items-center gap-3 px-3 py-2.5 rounded-lg transition-all duration-150 hover:bg-sidebar-accent"
              [ngClass]="{
                'text-sidebar-foreground/80 hover:text-sidebar-foreground': !isActive(item.url),
                'text-primary-foreground': isActive(item.url)
              }"
            >
              <app-icon [name]="item.icon" [className]="'w-5 h-5 flex-shrink-0'" />
              <span *ngIf="!collapsed()" class="font-medium text-sm animate-fade-in">{{ item.title }}</span>
            </a>
          </li>
        </ul>
      </nav>

      <div class="p-2 border-t border-sidebar-border">
        <button
          type="button"
          (click)="toggleCollapsed()"
          class="w-full flex items-center justify-center gap-2 px-3 py-2 rounded-lg text-sidebar-foreground/60 hover:text-sidebar-foreground hover:bg-sidebar-accent transition-colors"
        >
          <app-icon [name]="collapsed() ? 'chevron-right' : 'chevron-left'" [className]="'w-5 h-5'" />
          <span *ngIf="!collapsed()" class="text-sm">Colapsar</span>
        </button>
      </div>
    </aside>
  `,
})
export class AppSidebarComponent {
  private router = inject(Router);
  readonly collapsed = signal(false);
  readonly menuItems = menuItems;

  toggleCollapsed() {
    this.collapsed.update((value) => !value);
  }

  isActive(url: string) {
    return this.router.url === url || (url === '/proyectos' && this.router.url === '/');
  }
}
